version: "3.9"
services:
  webapp:
    image: node:18
    restart: always
    volumes:
      - ./api-fis:/app
      - npm-cache:/root/.npm
    working_dir: /app
    entrypoint: /app/scripts/run.sh
    command: npm run dev -- --hostname=0.0.0.0
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  npm-cache:
    external: false
